// <auto-generated />
import {
  createSvelteMvvmCommandFacade,
  derivedMvvmCollection,
  derivedMvvmProperty,
  derivedMvvmValidation,
  type SvelteMvvmStore,
} from "@runic-artifex/mvvm-svelte";
import type { SimpleTodoContract, AdvancedTodoContract } from "../../shared/todo-contract.g.js";

export function createSimpleTodoStores(
  store: SvelteMvvmStore,
  contract: SimpleTodoContract,
) {
  const newTitleBinding = derivedMvvmProperty(store, contract.newTitle);
  const newTitleErrors = derivedMvvmValidation(store, contract.newTitle);
  const itemsBinding = derivedMvvmCollection(store, contract.items);
  const addBinding = createSvelteMvvmCommandFacade(store, contract.add);
  const toggleBinding = createSvelteMvvmCommandFacade(store, contract.toggle);
  const removeBinding = createSvelteMvvmCommandFacade(store, contract.remove);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    items: itemsBinding,
    add: addBinding,
    toggle: toggleBinding,
    remove: removeBinding,
    dispose() {
      addBinding.dispose();
      toggleBinding.dispose();
      removeBinding.dispose();
    },
  } as const;
}

export function createAdvancedTodoStores(
  store: SvelteMvvmStore,
  contract: AdvancedTodoContract,
) {
  const newTitleBinding = derivedMvvmProperty(store, contract.newTitle);
  const newTitleErrors = derivedMvvmValidation(store, contract.newTitle);
  const newNotesBinding = derivedMvvmProperty(store, contract.newNotes);
  const newPriorityBinding = derivedMvvmProperty(store, contract.newPriority);
  const queryBinding = derivedMvvmProperty(store, contract.query);
  const filterBinding = derivedMvvmProperty(store, contract.filter);
  const itemsBinding = derivedMvvmCollection(store, contract.items);
  const diagnosticsBinding = derivedMvvmCollection(store, contract.diagnostics);
  const stateBinding = derivedMvvmProperty(store, contract.state);
  const addBinding = createSvelteMvvmCommandFacade(store, contract.add);
  const applyFilterBinding = createSvelteMvvmCommandFacade(store, contract.applyFilter);
  const toggleBinding = createSvelteMvvmCommandFacade(store, contract.toggle);
  const deleteBinding = createSvelteMvvmCommandFacade(store, contract.delete);
  const clearCompletedBinding = createSvelteMvvmCommandFacade(store, contract.clearCompleted);
  const importBinding = createSvelteMvvmCommandFacade(store, contract.import);
  const cancelImportBinding = createSvelteMvvmCommandFacade(store, contract.cancelImport);
  const wizardStartBinding = createSvelteMvvmCommandFacade(store, contract.wizardStart);
  const wizardNextBinding = createSvelteMvvmCommandFacade(store, contract.wizardNext);
  const wizardBackBinding = createSvelteMvvmCommandFacade(store, contract.wizardBack);
  const wizardFinishBinding = createSvelteMvvmCommandFacade(store, contract.wizardFinish);
  const wizardCancelBinding = createSvelteMvvmCommandFacade(store, contract.wizardCancel);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    newNotes: newNotesBinding,
    newPriority: newPriorityBinding,
    query: queryBinding,
    filter: filterBinding,
    items: itemsBinding,
    diagnostics: diagnosticsBinding,
    state: stateBinding,
    add: addBinding,
    applyFilter: applyFilterBinding,
    toggle: toggleBinding,
    delete: deleteBinding,
    clearCompleted: clearCompletedBinding,
    import: importBinding,
    cancelImport: cancelImportBinding,
    wizardStart: wizardStartBinding,
    wizardNext: wizardNextBinding,
    wizardBack: wizardBackBinding,
    wizardFinish: wizardFinishBinding,
    wizardCancel: wizardCancelBinding,
    dispose() {
      addBinding.dispose();
      applyFilterBinding.dispose();
      toggleBinding.dispose();
      deleteBinding.dispose();
      clearCompletedBinding.dispose();
      importBinding.dispose();
      cancelImportBinding.dispose();
      wizardStartBinding.dispose();
      wizardNextBinding.dispose();
      wizardBackBinding.dispose();
      wizardFinishBinding.dispose();
      wizardCancelBinding.dispose();
    },
  } as const;
}
