#!/usr/bin/env node
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join, resolve } from "node:path";
import process from "node:process";

export const RECEIPT_SCHEMA = "runic.current-hosted-sveltekit/1";
export const REPEAT_RECEIPT_SCHEMA = "runic.current-hosted-sveltekit-repeat/1";
export const NPM_FEED = "w30-003-local-candidate-npm-feed";
export const CANDIDATE_NAMES = ["@runic-artifex/svelte", "@runic-artifex/sveltekit"];
const root = resolve(import.meta.dirname, "../..");
const archives = (process.env.RUNIC_CURRENT_HOSTED_SVELTEKIT_NPM_ARCHIVES ?? "").split(",").filter(Boolean).map((path) => resolve(path));
const same = (left, right) => JSON.stringify(left) === JSON.stringify(right);
const sha256 = async (path) => createHash("sha256").update(await readFile(path)).digest("hex");

function run(command, args, cwd, env = {}) {
  return new Promise((done) => {
    const child = spawn(command, args, { cwd, env: { ...process.env, ...env }, stdio: ["ignore", "pipe", "pipe"] });
    const output = [];
    child.stdout.on("data", (value) => output.push(value)); child.stderr.on("data", (value) => output.push(value));
    child.on("error", (error) => done({ ok: false, exitCode: null, reasonCode: error.code === "ENOENT" ? "command-not-found" : "command-spawn-failed", output: "" }));
    child.on("close", (exitCode) => done({ ok: exitCode === 0, exitCode, reasonCode: exitCode === 0 ? null : "command-exit-nonzero", output: Buffer.concat(output).toString("utf8") }));
  });
}
function phase(name, argv, result) { return { name, argv, status: result.ok ? "passed" : "failed", exitCode: result.exitCode, reasonCode: result.reasonCode }; }
function requireSuccess(name, result) { if (!result.ok) throw new Error(`${name} failed: ${result.reasonCode}\n${result.output.slice(-4096)}`); }

const registry = "import { createReadStream,readFileSync } from 'node:fs';import { createServer } from 'node:http';import { createHash } from 'node:crypto';import { basename } from 'node:path';import { execFileSync } from 'node:child_process';const entries=new Map(process.argv.slice(1).map(a=>{const manifest=JSON.parse(execFileSync('tar',['-xOf',a,'package/package.json'],{encoding:'utf8'}));return [manifest.name,{a,manifest}]}));const server=createServer((q,s)=>{const p=new URL(q.url??'/','http://localhost').pathname;for(const [n,e]of entries){const a='/archive/'+basename(e.a);if(decodeURIComponent(p.slice(1))===n){const tarball='http://127.0.0.1:'+server.address().port+a;const integrity='sha512-'+createHash('sha512').update(readFileSync(e.a)).digest('base64');s.writeHead(200,{'content-type':'application/json'});return s.end(JSON.stringify({name:n,'dist-tags':{latest:e.manifest.version},versions:{[e.manifest.version]:{...e.manifest,dist:{tarball,integrity}}}}))}if(p===a){s.writeHead(200);return createReadStream(e.a).pipe(s)}}s.writeHead(404);s.end()});server.listen(0,'127.0.0.1',()=>process.stdout.write('http://127.0.0.1:'+server.address().port+'\\n'));process.on('SIGTERM',()=>server.close(()=>process.exit(0)));";

async function startRegistry() {
  if (archives.length !== CANDIDATE_NAMES.length) throw new Error("RUNIC_CURRENT_HOSTED_SVELTEKIT_NPM_ARCHIVES must name exact current Runic Svelte and SvelteKit archives");
  const manifests = [];
  for (const archive of archives) {
    const result = await run("tar", ["-xOf", archive, "package/package.json"], root); requireSuccess(`read ${basename(archive)}`, result); manifests.push(JSON.parse(result.output));
  }
  if (!same(manifests.map((item) => item.name).sort(), [...CANDIDATE_NAMES].sort())) throw new Error("candidate archives must contain exactly current Runic Svelte and SvelteKit packages");
  const child = spawn("node", ["--input-type=module", "--eval", registry, ...archives], { cwd: root, stdio: ["ignore", "pipe", "pipe"] });
  const url = await new Promise((resolveUrl, reject) => { const timer = setTimeout(() => reject(new Error("local npm registry did not bind")), 5000); child.stdout.once("data", (value) => { clearTimeout(timer); resolveUrl(value.toString("utf8").trim()); }); child.once("error", reject); child.stderr.once("data", (value) => reject(new Error(value.toString("utf8")))); });
  return { child, url, manifests };
}

const appHtml = '<!doctype html><html lang="%runic.locale%"><head><meta charset="utf-8" />%sveltekit.head%</head><body><div style="display:contents">%sveltekit.body%</div></body></html>\n';
const i18n = 'import { createRunicLocaleRouting } from "@runic-artifex/sveltekit/translations"; export const routing=createRunicLocaleRouting({locales:["en","de"],baseLocale:"en",baseLocalePath:"prefixed"});\n';
const service = 'import { RUNIC_HOSTED_SESSION_PATH } from "@runic-artifex/sveltekit/hosted"; export async function loadSession({path,cookie}) { if(path!==RUNIC_HOSTED_SESSION_PATH) throw new Error("unexpected C# service route"); if(cookie==="__Host-runic-session=operator") return Response.json({subject:"operator",displayName:"Operator",roles:["operator"]}); if(cookie==="__Host-runic-session=viewer") return Response.json({subject:"viewer",displayName:"Viewer",roles:["viewer"]}); return new Response(null,{status:401}); }\n';
const generatedMessages = '// <auto-generated />\nexport function hostedTitle(options:{locale:"en"|"de"}):string { switch(options.locale){case "en":return "Welcome";case "de":return "Willkommen";} }\n';
export const GENERATED_TRANSLATION = Object.freeze({
  module: "generated-messages.ts",
  requestLocale: "explicit",
  sourceSha256: createHash("sha256").update(generatedMessages).digest("hex"),
});
const hooks = 'import { error } from "@sveltejs/kit"; import { createRunicLocaleHandle } from "@runic-artifex/sveltekit/translations"; import { routing } from "$lib/i18n.js"; const localeHandle=createRunicLocaleHandle(routing,{persistLocale:true}); export const handle=async ({event,resolve})=>{const segment=event.url.pathname.split("/")[1]; if(!routing.isLocale(segment)) error(404,"Unsupported Runic locale."); return localeHandle({event,resolve});};\n';
const pageServer = 'import { createRunicHostedSsrLoad } from "@runic-artifex/sveltekit/hosted"; import { routing } from "$lib/i18n.js"; import { loadSession } from "$lib/service.server.js"; export const load=createRunicHostedSsrLoad(routing,{loadSession});\n';
const bridge = '<script lang="ts">import { onMount } from "svelte"; import { startRunicHostedBridgeAfterBootstrap } from "@runic-artifex/svelte/hosted"; let { bootstrap }: { bootstrap: { schema: "runic.hosted-bootstrap/1"; fingerprint: string; session: { subject: string } } } = $props(); const bridge={start:async()=>{document.documentElement.dataset.runicHostedBridge=bootstrap.session.subject;},dispose:async()=>{delete document.documentElement.dataset.runicHostedBridge;}}; onMount(()=>{if(!startRunicHostedBridgeAfterBootstrap(bootstrap,bridge)) return; return()=>{void bridge.dispose();};});</script><output data-hosted-bridge>{bootstrap.fingerprint}</output>\n';
const page = '<script lang="ts">import BridgeBootstrap from "$lib/BridgeBootstrap.svelte"; import { routing } from "$lib/i18n.js"; import { hostedTitle } from "$lib/generated-messages.js"; let { data }: import("./$types").PageProps=$props();</script><svelte:head><meta name="runic-hosted-bootstrap" content={data.bootstrap.fingerprint}/><link rel="canonical" href={routing.canonicalUrl("/"+data.bootstrap.locale,data.bootstrap.locale)}/></svelte:head><h1>{hostedTitle({locale:data.bootstrap.locale})}</h1><p data-subject>{data.bootstrap.session.subject}</p><p data-locale>{data.bootstrap.locale}</p><BridgeBootstrap bootstrap={data.bootstrap}/>\n';
const hydrateConfig = 'import { svelte } from "@sveltejs/vite-plugin-svelte"; import { defineConfig } from "vite"; export default defineConfig({plugins:[svelte()],build:{outDir:"hydration-dist",lib:{entry:"test/hydrate-entry.js",formats:["es"],fileName:()=>"bridge-bootstrap.mjs"}}});\n';
const hydrateEntry = 'import { mount,tick,unmount } from "svelte"; import BridgeBootstrap from "../src/lib/BridgeBootstrap.svelte"; export async function run(){const bootstrap={schema:"runic.hosted-bootstrap/1",fingerprint:"runic-hosted-1234abcd",session:{subject:"operator"}}; document.head.innerHTML=`<meta name="runic-hosted-bootstrap" content="${bootstrap.fingerprint}">`;let component=mount(BridgeBootstrap,{target:document.body,props:{bootstrap}});await tick();if(document.documentElement.dataset.runicHostedBridge!=="operator")throw new Error("matching bootstrap did not start bridge");await unmount(component);if(document.documentElement.dataset.runicHostedBridge!==undefined)throw new Error("bridge did not dispose");document.head.innerHTML=`<meta name="runic-hosted-bootstrap" content="runic-hosted-deadbeef">`;component=mount(BridgeBootstrap,{target:document.body,props:{bootstrap}});await tick();if(document.documentElement.dataset.runicHostedBridge!==undefined||document.documentElement.dataset.runicHostedHydration!=="mismatch")throw new Error("mismatched bootstrap did not fail closed");await unmount(component);}\n';
const hydrate = 'import { Window } from "happy-dom"; const dom=new Window(); Object.assign(globalThis,{window:dom,document:dom.document,HTMLElement:dom.HTMLElement,HTMLMetaElement:dom.HTMLMetaElement,Element:dom.Element,Node:dom.Node,Text:dom.Text,Comment:dom.Comment,Event:dom.Event,CustomEvent:dom.CustomEvent}); const {run}=await import("../hydration-dist/bridge-bootstrap.mjs"); await run(); console.log("hosted-sveltekit-hydration-ok");\n';
const ssr = 'import assert from "node:assert/strict"; import { spawn } from "node:child_process"; const vite=spawn(process.execPath,["./node_modules/vite/bin/vite.js","dev","--host","127.0.0.1","--port","0"],{stdio:["ignore","pipe","pipe"]}); const output=[]; vite.stdout.on("data",value=>output.push(value)); vite.stderr.on("data",value=>output.push(value)); const base=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error("SvelteKit server did not start")),10000); const read=value=>{const match=value.toString().match(/http:\\/\\/127\\.0\\.0\\.1:(\\d+)/);if(match){clearTimeout(timer);resolve("http://127.0.0.1:"+match[1]);}};vite.stdout.on("data",read);vite.stderr.on("data",read);vite.once("error",reject);}); try { const requests=Array.from({length:20},(_,index)=>{const german=index%2===1;const locale=german?"de":"en";const subject=german?"viewer":"operator";return fetch(base+"/"+locale,{headers:{cookie:"tracking=ignored; __Host-runic-session="+subject+"; runic_locale="+(german?"en":"de")}}).then(async response=>({response,html:await response.text(),locale,subject}));}); const results=await Promise.all(requests); for(const {response,html,locale,subject} of results){assert.equal(response.status,200);assert.match(html,new RegExp(`<html lang="${locale}">`));assert.match(html,locale==="de"?/Willkommen/:/Welcome/);assert.match(html,new RegExp(`<p data-subject(?:="")?>${subject}<\\/p>`));assert.equal(response.headers.get("set-cookie")?.includes("runic_locale="+locale),true);} assert.equal((await fetch(base+"/fr",{headers:{cookie:"__Host-runic-session=operator"}})).status,404);assert.equal((await fetch(base+"/en")).status,401);console.log("hosted-sveltekit-ssr-ok"); } finally { vite.kill("SIGTERM"); await new Promise(resolve=>vite.once("exit",resolve)); }\n';

export function verifyReceipt(receipt) {
  const errors = [];
  if (receipt?.schema !== RECEIPT_SCHEMA) errors.push("receipt schema mismatch");
  if (!same(receipt?.feeds, { npm: NPM_FEED }) || !same(receipt?.isolation, { npmCache: ".npm-cache" })) errors.push("candidate isolation mismatch");
  if (!same(receipt?.generatedTranslation, GENERATED_TRANSLATION)) errors.push("generated translation evidence mismatch");
  if (!Array.isArray(receipt?.candidates) || receipt.candidates.length !== CANDIDATE_NAMES.length || receipt.candidates.some((item) => !CANDIDATE_NAMES.includes(item?.identity) || item.source !== NPM_FEED || typeof item.version !== "string" || !item.integrity || !/^[a-f0-9]{64}$/.test(item.archiveSha256 ?? ""))) errors.push("npm provenance mismatch");
  const expected = [["npm-install", ["npm", "install", "--ignore-scripts", "--legacy-peer-deps"]], ["svelte-check", ["npm", "run", "check"]], ["ssr-concurrency", ["node", "test/ssr.mjs"]], ["hydration-bootstrap", ["npm", "run", "hydrate"]]];
  if (!Array.isArray(receipt?.phases) || receipt.phases.length !== expected.length) errors.push("phase evidence malformed"); else expected.forEach(([name, argv], index) => { const item = receipt.phases[index]; if (!item || item.name !== name || !same(item.argv, argv) || item.status !== "passed" || item.exitCode !== 0 || item.reasonCode !== null) errors.push(`${name} evidence malformed`); });
  return { ok: errors.length === 0, errors };
}
export function verifyRepeatedReceipt(receipt) { const errors = []; if (receipt?.schema !== REPEAT_RECEIPT_SCHEMA || !Array.isArray(receipt?.journeys) || receipt.journeys.length !== 2) errors.push("repeat receipt malformed"); else { receipt.journeys.forEach((journey) => errors.push(...verifyReceipt(journey).errors)); if (!same(receipt.journeys[0], receipt.journeys[1])) errors.push("hosted SvelteKit journeys are not deterministic"); } return { ok: errors.length === 0, errors }; }

async function one() {
  const directory = await mkdtemp(join(tmpdir(), "runic-current-hosted-sveltekit-")); const environment = { npm_config_cache: join(directory, ".npm-cache") }; let localRegistry;
  try {
    localRegistry = await startRegistry(); const versions = Object.fromEntries(localRegistry.manifests.map((item) => [item.name, item.version]));
    const packageJson = { private: true, type: "module", scripts: { check: "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json", hydrate: "vite build --config hydrate.vite.config.js && node --conditions=browser test/hydrate.mjs" }, devDependencies: { "@runic-artifex/svelte": versions["@runic-artifex/svelte"], "@runic-artifex/sveltekit": versions["@runic-artifex/sveltekit"], "@sveltejs/kit": "2.70.2", "@sveltejs/vite-plugin-svelte": "7.2.0", "happy-dom": "20.11.2", "svelte": "5.56.8", "svelte-check": "4.7.5", "typescript": "5.9.3", "vite": "8.2.1" } };
    await Promise.all([mkdir(join(directory, "src/lib"), { recursive: true }), mkdir(join(directory, "src/routes/[locale]"), { recursive: true }), mkdir(join(directory, "test"), { recursive: true })]);
    await Promise.all([writeFile(join(directory, "package.json"), JSON.stringify(packageJson, null, 2) + "\n"), writeFile(join(directory, ".npmrc"), "@runic-artifex:registry=" + localRegistry.url + "\n"), writeFile(join(directory, "svelte.config.js"), "export default {};\n"), writeFile(join(directory, "vite.config.js"), 'import { sveltekit } from "@sveltejs/kit/vite"; import { defineConfig } from "vite"; export default defineConfig({plugins:[sveltekit()]});\n'), writeFile(join(directory, "tsconfig.json"), '{"extends":"./.svelte-kit/tsconfig.json","compilerOptions":{"allowJs":true,"checkJs":true}}\n'), writeFile(join(directory, "src/app.html"), appHtml), writeFile(join(directory, "src/lib/i18n.ts"), i18n), writeFile(join(directory, "src/lib/service.server.ts"), service), writeFile(join(directory, "src/lib/generated-messages.ts"), generatedMessages), writeFile(join(directory, "src/lib/BridgeBootstrap.svelte"), bridge), writeFile(join(directory, "src/hooks.server.ts"), hooks), writeFile(join(directory, "src/routes/[locale]/+page.server.ts"), pageServer), writeFile(join(directory, "src/routes/[locale]/+page.svelte"), page), writeFile(join(directory, "hydrate.vite.config.js"), hydrateConfig), writeFile(join(directory, "test/hydrate-entry.js"), hydrateEntry), writeFile(join(directory, "test/hydrate.mjs"), hydrate), writeFile(join(directory, "test/ssr.mjs"), ssr)]);
    const phases = []; for (const [name, command, args] of [["npm-install", "npm", ["install", "--ignore-scripts", "--legacy-peer-deps"]], ["svelte-check", "npm", ["run", "check"]], ["ssr-concurrency", "node", ["test/ssr.mjs"]], ["hydration-bootstrap", "npm", ["run", "hydrate"]]]) { const result = await run(command, args, directory, environment); phases.push(phase(name, [command, ...args], result)); requireSuccess(name, result); }
    const lock = JSON.parse(await readFile(join(directory, "package-lock.json"), "utf8")); const candidates = await Promise.all(localRegistry.manifests.map(async (manifest) => { const item = lock.packages?.[`node_modules/${manifest.name}`]; if (!item || item.version !== manifest.version || !item.resolved?.startsWith(localRegistry.url) || !item.integrity) throw new Error(`npm provenance failed closed for ${manifest.name}`); return { identity: manifest.name, version: manifest.version, source: NPM_FEED, integrity: item.integrity, archiveSha256: await sha256(archives[localRegistry.manifests.indexOf(manifest)]) }; }));
    const receipt = { schema: RECEIPT_SCHEMA, feeds: { npm: NPM_FEED }, isolation: { npmCache: ".npm-cache" }, generatedTranslation: GENERATED_TRANSLATION, candidates, phases }; const report = verifyReceipt(receipt); if (!report.ok) throw new Error(report.errors.join("\n")); return receipt;
  } finally { if (localRegistry) localRegistry.child.kill("SIGTERM"); await rm(directory, { recursive: true, force: true }); }
}
async function main() { const [command, path] = process.argv.slice(2); if (command === "run-twice" && !path) { const receipt = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [await one(), await one()] }; const report = verifyRepeatedReceipt(receipt); if (!report.ok) throw new Error(report.errors.join("\n")); process.stdout.write(JSON.stringify(receipt, null, 2) + "\n"); return; } if (command === "verify-twice" && path) { const report = verifyRepeatedReceipt(JSON.parse(await readFile(path, "utf8"))); if (!report.ok) throw new Error(report.errors.join("\n")); return; } throw new Error("Usage: node eng/current-hosted-sveltekit/verify.mjs <run-twice|verify-twice> [receipt.json]"); }
if (import.meta.main) main().catch((error) => { process.stderr.write(error.message + "\n"); process.exitCode = 1; });
