import assert from "node:assert/strict";
import test from "node:test";
import { verifyReceipt } from "./verify.mjs";

function journey() { return { schema: "runic-w40-mf2-subset-consumer-receipt/1", profile: "runic-mf2-subset/1", isolation: { nugetGlobalPackagesFolder: ".nuget/packages", nugetHttpCachePath: ".nuget/http-cache", dotnetCliHome: ".dotnet", npmCache: ".npm-cache" }, manifest: { catalog: "w40", contractFingerprint: `sha256:${"a".repeat(64)}`, esmAbiVersion: 3, runtimeAbiVersion: 1, generatorVersion: 1, sha256: "b".repeat(64) }, parity: { locales: ["de", "en"], messages: { en: { welcome: "Hello Ada" }, de: { welcome: "Hallo Ada" } } }, negativeGates: ["unsupported-mf2-function", "abi-mismatch", "schema-mismatch", "stale-generated-manifest", "forged-generated-manifest"], nugetCandidates: ["Runic.Translations", "Runic.Translations.Build", "dotnet-runic-translations"].map(identity => ({ identity, version: "1.0.0", source: "exact-local", contentHash: "sha512-fixture", archiveSha256: "c".repeat(64) })), npmCandidate: { identity: "@runic-artifex/vite-plugin-runic-translations", version: "1.0.0", source: "exact-local", integrity: "sha512-fixture", archiveSha256: "d".repeat(64) }, phases: ["restore", "tool-restore", "build", "npm-install", "parity"].map(name => ({ name, exitCode: 0 })) }; }
function receipt() { const first = journey(); return { schema: "runic-w40-mf2-subset-consumer-repeat-receipt/1", journeys: [first, structuredClone(first)] }; }

test("W40 receipt accepts two exact local MF2 subset journeys", () => assert.equal(verifyReceipt(receipt()).ok, true));
test("W40 receipt rejects forged provenance, manifest, and gate evidence", () => { const value = receipt(); value.journeys[1].manifest.contractFingerprint = `sha256:${"0".repeat(64)}`; value.journeys[1].npmCandidate.source = "public"; value.journeys[1].negativeGates.pop(); const report = verifyReceipt(value); assert.equal(report.ok, false); assert.match(report.errors.join("\n"), /deterministic|provenance|negative/); });
