#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const root = resolve(import.meta.dirname, '../..');
const schema = 'runic.local-1.0-readiness-index/1', repeatSchema = 'runic.local-1.0-readiness-index-repeat/1';
const profiles = ['csharp-host', 'local-application-bridge', 'editor-desktop', 'd008-hosted-product'];
const required = ['audit', 'documentation', 'operator', 'freeze', 'clean-room', 'support-certification', 'native', 'w04', 'w30', 'w40', 'w50-support', 'w50-recovery', 'w50-quality', 'w60-candidate', 'w60-tool', 'w60-preflight', 'w60-handoff', 'package-gate'];
const citations = { 'w30-rollout': 'w30', 'w40-localization': 'w40', 'w50-support': 'w50-support', 'w50-recovery': 'w50-recovery', 'w50-quality': 'w50-quality', 'w60-candidate': 'w60-candidate', 'w60-tool': 'w60-tool', 'w60-preflight': 'w60-preflight', 'w60-handoff': 'w60-handoff' };
const exclusions = ['unsigned', 'non-public', 'publication', 'signing', 'version-assignment', 'update', 'deployment', 'automatic-operator-action', 'c-webui-abi-source-work', 'browser-platform-success', 'native-platform-success', 'hosted-topology-change'];
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b), digest = (b) => createHash('sha256').update(b).digest('hex');
const fail = (m) => { throw new Error(`local readiness index: ${m}`); };
async function read(path, name) { const bytes = await readFile(resolve(path)); try { return { sha256: digest(bytes), value: JSON.parse(bytes) }; } catch { fail(`${name} must be JSON`); } }
function journey(value, schema, name) { const repeat = schema.replace(/\/1$/, '-repeat/1'); if (value?.schema !== repeat || value.journeys?.length !== 2 || !same(value.journeys[0], value.journeys[1]) || value.journeys[0]?.schema !== schema) fail(`${name} is not deterministic`); return value.journeys[0]; }
function citation(freeze, id) { const values = freeze.citations?.filter((x) => x.id === id); if (values?.length !== 1) fail(`freeze must cite ${id} exactly once`); return values[0]; }
async function verify(path, input, value, name) { const module = await import(pathToFileURL(join(root, path)).href); const report = module.verifyReceipt(input.value, value); if (!report?.ok) fail(`${name} verifier rejected input`); }

async function collect(paths) {
  const inputs = Object.fromEntries(await Promise.all(required.map(async (name) => [name, await read(paths[name], name)])));
  const audit = journey(inputs.audit.value, 'runic.local-nonpublic-readiness-audit/1', 'audit');
  const docs = journey(inputs.documentation.value, 'runic.local-documentation-support-parity/1', 'documentation');
  const operator = journey(inputs.operator.value, 'runic.local-operator-rehearsal/1', 'operator');
  const freeze = journey(inputs.freeze.value, 'runic.controlled-nonpublic-profile-freeze/1', 'freeze');
  const clean = journey(inputs['clean-room'].value, 'runic.controlled-clean-room-conformance/1', 'clean room');
  const support = journey(inputs['support-certification'].value, 'runic.support-certification/1', 'support');
  const native = journey(inputs.native.value, 'runic.native-shell-capability-certification/1', 'native');
  await Promise.all([
    verify('eng/current-readiness-audit/verify.mjs', inputs.audit, audit, 'audit'), verify('eng/current-documentation-support-parity/verify.mjs', inputs.documentation, docs, 'documentation'), verify('eng/current-operator-rehearsal/verify.mjs', inputs.operator, operator, 'operator'), verify('eng/current-controlled-clean-room/verify.mjs', inputs['clean-room'], clean, 'clean room'), verify('eng/current-support-certification/verify.mjs', inputs['support-certification'], support, 'support'), verify('eng/current-native-shell-certification/verify.mjs', inputs.native, native, 'native'),
  ]);
  if (audit.publication !== 'forbidden' || !same(Object.keys(audit.retainedProfiles ?? {}).sort(), [...profiles].sort()) || audit.evidence?.w70Freeze?.sha256 !== inputs.freeze.sha256 || audit.evidence?.w70CleanRoom?.sha256 !== inputs['clean-room'].sha256 || audit.evidence?.w70Support?.sha256 !== inputs['support-certification'].sha256 || audit.evidence?.w70Native?.sha256 !== inputs.native.sha256 || audit.evidence?.w04Foundation?.sha256 !== inputs.w04.sha256) fail('audit does not bind the retained train');
  if (!same(clean.frozenProfile?.profiles, audit.retainedProfiles) || !same(support.frozenProfile?.profiles, audit.retainedProfiles) || !same(native.frozenProfile?.profiles, audit.retainedProfiles) || docs.evidence?.audit?.sha256 !== inputs.audit.sha256 || operator.evidence?.audit?.sha256 !== inputs.audit.sha256 || operator.evidence?.documentation?.sha256 !== inputs.documentation.sha256) fail('W80 chain is cross-profile or incomplete');
  for (const [id, name] of Object.entries(citations)) { const item = citation(freeze, id); if (item.sha256 !== inputs[name].sha256 || item.schema !== inputs[name].value.schema) fail(`${id} is stale, replayed, or conflicting`); }
  if (audit.postFreezePackageGate?.sha256 !== inputs['package-gate'].sha256 || audit.postFreezePackageGate?.status !== 'passed-not-retained' || inputs['package-gate'].value?.postFreeze !== true || inputs['package-gate'].value?.retainedProfile !== false || inputs['package-gate'].value?.packageVersion !== '0.2.0-preview.w80001') fail('post-freeze package gate was represented as retained');
  if (native.abiOracle?.status !== 'passing' || native.observedProfile?.certifiedResult?.status !== 'unavailable' || native.observedProfile?.certifiedResult?.capability !== 'private-file-handler-streaming-unavailable' || operator.migration?.guidance !== 'user-performed-verified-manual-replacement' || !same(operator.recovery, { completeRollback: true, mutationBeforeRecovery: 'rejected', staleBridgeState: 'rejected', diagnostics: 'sanitized-counts' })) fail('native, migration, or recovery claim was softened');
  return { schema, publication: 'forbidden', retainedProfiles: audit.retainedProfiles, evidence: Object.fromEntries(required.map((name) => [name, { sha256: inputs[name].sha256, schema: inputs[name].value.schema }])), claims: { 'csharp-host': ['compatibility', 'direct-tool-migration', 'support-recovery', 'packaging', 'documentation'], 'local-application-bridge': ['compatibility', 'structural-quality', 'documentation'], 'editor-desktop': ['compatibility', 'manual-replacement', 'localization', 'support-recovery', 'structural-quality', 'packaging', 'documentation', 'native-boundary'], 'd008-hosted-product': ['compatibility', 'hosted-rollout', 'localization', 'documentation'] }, postFreezePackageGate: { status: 'passed-not-retained', source: inputs['package-gate'].value.source, packageVersion: inputs['package-gate'].value.packageVersion }, nativeBoundary: { abiOracle: 'passing', linuxX64: 'private-file-handler-streaming-unavailable', platformSuccess: 'not-claimed' }, exclusions, externalActions: { requests: 0, publications: 0, signatures: 0, updates: 0, uploads: 0, releases: 0, tags: 0 } };
}

export function verifyReceipt(value, expected) { const errors = []; if (value?.schema !== repeatSchema || value.journeys?.length !== 2 || !same(value.journeys?.[0], value.journeys?.[1])) errors.push('two deterministic index journeys are required'); if (expected && !same(value?.journeys?.[0], expected)) errors.push('receipt differs from exact local inputs'); for (const item of value?.journeys ?? []) if (item?.schema !== schema || item.publication !== 'forbidden' || !same(Object.keys(item.retainedProfiles ?? {}).sort(), [...profiles].sort()) || !same(Object.keys(item.evidence ?? {}).sort(), [...required].sort()) || !Object.values(item.evidence ?? {}).every((x) => /^[a-f0-9]{64}$/.test(x.sha256 ?? '') && typeof x.schema === 'string') || !same(Object.keys(item.claims ?? {}).sort(), [...profiles].sort()) || !same(item.exclusions, exclusions) || !same(item.nativeBoundary, { abiOracle: 'passing', linuxX64: 'private-file-handler-streaming-unavailable', platformSuccess: 'not-claimed' }) || item.postFreezePackageGate?.status !== 'passed-not-retained' || item.postFreezePackageGate?.packageVersion !== '0.2.0-preview.w80001' || !same(item.externalActions, { requests: 0, publications: 0, signatures: 0, updates: 0, uploads: 0, releases: 0, tags: 0 })) errors.push('readiness-index boundary mismatch'); return { ok: errors.length === 0, errors }; }
async function isolated(paths) { const directory = await mkdtemp(join(tmpdir(), 'runic-w80-index-')); try { const copied = {}; for (const name of required) { copied[name] = join(directory, `${name}.json`); await cp(resolve(paths[name]), copied[name]); } return await collect(copied); } finally { await rm(directory, { recursive: true, force: true }); } }
export async function runTwice(paths) { const value = { schema: repeatSchema, journeys: [await isolated(paths), await isolated(paths)] }; const report = verifyReceipt(value); if (!report.ok) fail(report.errors.join('; ')); return value; }
function args(argv) { const values = {}; for (let i = 0; i < argv.length; i += 2) { if (!argv[i]?.startsWith('--') || !argv[i + 1] || values[argv[i]]) fail('usage'); values[argv[i].slice(2)] = argv[i + 1]; } if (!same(Object.keys(values).filter((x) => x !== 'receipt').sort(), [...required].sort())) fail('all readiness evidence inputs are required'); return values; }
async function main(argv) { const [command, ...rest] = argv, options = args(rest); if (command === 'run-twice' && !options.receipt) return JSON.stringify(await runTwice(options), null, 2); if (command === 'verify-twice' && options.receipt) { const actual = JSON.parse(await readFile(options.receipt)); const expected = await runTwice(options), report = verifyReceipt(actual, expected.journeys[0]); if (!report.ok || !same(actual, expected)) fail(report.errors.concat('receipt differs from exact local inputs').join('; ')); return; } fail('usage'); }
if (import.meta.main) main(process.argv.slice(2)).then((output) => { if (output) process.stdout.write(`${output}\n`); }).catch((error) => { process.stderr.write(`${error.message}\n`); process.exitCode = 1; });
