import assert from 'node:assert/strict';
import test from 'node:test';
import { BRIDGE_CONTRACT, CANDIDATE_NAMES, NPM_FEED, RECEIPT_SCHEMA, REPEAT_RECEIPT_SCHEMA, verifyReceipt, verifyRepeatedReceipt } from './verify.mjs';
const authority = { path: 'runic.release.json', revision: 'a'.repeat(40), tree: 'b'.repeat(40), digest: 'c'.repeat(64), publicPackageCounts: { nuget: 1, npm: 1 }, before: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' }, after: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' } };
const phase = (name, argv) => ({ name, argv, status: 'passed', exitCode: 0, reasonCode: null });
function receipt() { return { schema: RECEIPT_SCHEMA, feeds: { npm: NPM_FEED }, isolation: { npmCache: '.npm-cache' }, releaseManifest: structuredClone(authority), bridgeContract: structuredClone(BRIDGE_CONTRACT), bridgeManifestSha256: 'b'.repeat(64), candidates: CANDIDATE_NAMES.map((identity) => ({ identity, version: '0.1.0', source: NPM_FEED, integrity: 'sha512-fixture', archiveSha256: 'a'.repeat(64) })), phases: [phase('npm-install', ['npm', 'install', '--ignore-scripts']), phase('frontend-build', ['npm', 'run', 'build']), phase('headless-provider', ['node', 'consumer.mjs'])] }; }
test('Svelte controller receipt accepts exact local candidate evidence', () => assert.deepEqual(verifyReceipt(receipt(), authority), { ok: true, errors: [] }));
test('Svelte controller receipt rejects forged contract, candidate provenance, and provider evidence', () => { const value = receipt(); value.bridgeContract.fingerprint = 'forged'; value.candidates[0].source = 'public'; value.phases[2].status = 'failed'; const report = verifyReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /shared generated contract|npm provenance|headless-provider/); });
test('Svelte controller receipt requires deterministic journeys', () => { const value = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [receipt(), receipt()] }; assert.deepEqual(verifyRepeatedReceipt(value, authority), { ok: true, errors: [] }); value.journeys[1].candidates[1].version = 'forged'; const report = verifyRepeatedReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /not deterministic/); });
