<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>RunicToolkit.Samples.Todo.Shared</AssemblyName>
    <RootNamespace>RunicToolkit.Samples.Todo</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="RunicToolkit.Collections" />
    <PackageReference Include="RunicFlow" />
  </ItemGroup>
</Project>
