<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RunicToolkit.Samples.Todo.React</AssemblyName>
    <RootNamespace>RunicToolkit.Samples.Todo.React</RootNamespace>
    <TodoFrontendWorkspace>@runic-artifex/sample-todo-react</TodoFrontendWorkspace>
    <TodoFrontendDirectory>react</TodoFrontendDirectory>
  </PropertyGroup>
  <Import Project="../Todo.Frontends/TodoFrontendSample.props" />
</Project>
