<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>RunicToolkit.Samples.SimpleTodo</AssemblyName>
    <RootNamespace>RunicToolkit.Samples.SimpleTodo</RootNamespace>
    <IsPackable>false</IsPackable>
    <DebugType>none</DebugType>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RunicToolkitFrontendNodeEnabled>true</RunicToolkitFrontendNodeEnabled>
    <RunicToolkitFrontendWorkspace>@runic-artifex/sample-todo-cwhtml</RunicToolkitFrontendWorkspace>
    <RunicToolkitFrontendPackageDirectory>$(MSBuildProjectDirectory)/../Todo.Cwhtml.Frontend</RunicToolkitFrontendPackageDirectory>
    <RunicToolkitFrontendOutputDirectory>$(MSBuildProjectDirectory)/../Todo.Cwhtml.Frontend/dist</RunicToolkitFrontendOutputDirectory>
    <RunicToolkitFrontendWorkspaceRoot>$(MSBuildProjectDirectory)/../..</RunicToolkitFrontendWorkspaceRoot>
    <RunicToolkitFrontendWebRoot>www</RunicToolkitFrontendWebRoot>
    <RunicToolkitFrontendViteDevServerEnabled>true</RunicToolkitFrontendViteDevServerEnabled>
    <RunicToolkitFrontendViteDevServerEntry>/src/main.js</RunicToolkitFrontendViteDevServerEntry>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsWebUi" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="RunicToolkit.Collections" />
    <PackageReference Include="RunicToolkit.Hosting" />
    <PackageReference Include="RunicToolkit.Hosting.Build" PrivateAssets="all" />
    <PackageReference Include="RunicToolkit.Hosting.CsWebUi" />
    <PackageReference Include="RunicToolkit.Hosting.CsWebUi.App" />
    <PackageReference Include="RunicToolkit.Hosting.GenericHost" />
    <PackageReference Include="RunicToolkit.Hosting.WebUi" />
    <PackageReference Include="RunicToolkit.Frontend.Sdk" PrivateAssets="all" />
    <PackageReference Include="RunicToolkit.MVVM.CommunityToolkit" />
    <PackageReference Include="RunicMarkup.Build" PrivateAssets="all" />
    <PackageReference Include="RunicMarkup.RunicToolkit.CommunityToolkit" PrivateAssets="all" />
    <PackageReference Include="RunicMarkup.RunicToolkit.Htmx" />
    <PackageReference Include="RunicMarkup.RunicToolkit.Htmx.Js" />
    <PackageReference Include="RunicMarkup.RunicToolkit.Htmx.CsWebUi" />
    <PackageReference Include="RunicMarkup.RunicToolkit.Htmx.CsWebUi.App" />
    <PackageReference Include="RunicMarkup.RunicToolkit.FrontendCompiler" PrivateAssets="all" />
    <ProjectReference Include="../Cwhtml.SampleComponents/RunicToolkit.Samples.Cwhtml.Components.csproj" />
    <ProjectReference Include="../Todo.Shared/Todo.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <CwhtmlCodeBehind Include="TodoRenderModel.cs" />
  </ItemGroup>
</Project>
