// <auto-generated />
import {
  useVueMvvmCollection,
  useVueMvvmCommandFacade,
  useVueMvvmProperty,
  useVueMvvmValidation,
  type VueMvvmAdapter,
} from "@runic-artifex/mvvm-vue";
import type { SimpleTodoContract, AdvancedTodoContract } from "../../shared/todo-contract.g.js";

export function useSimpleTodoBindings(
  contract: SimpleTodoContract,
  adapter?: VueMvvmAdapter,
) {
  const newTitleBinding = useVueMvvmProperty(contract.newTitle, adapter);
  const newTitleErrors = useVueMvvmValidation(contract.newTitle, adapter);
  const itemsBinding = useVueMvvmCollection(contract.items, adapter);
  const addBinding = useVueMvvmCommandFacade(contract.add, adapter);
  const toggleBinding = useVueMvvmCommandFacade(contract.toggle, adapter);
  const removeBinding = useVueMvvmCommandFacade(contract.remove, adapter);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    items: itemsBinding,
    add: addBinding,
    toggle: toggleBinding,
    remove: removeBinding,
  } as const;
}

export function useAdvancedTodoBindings(
  contract: AdvancedTodoContract,
  adapter?: VueMvvmAdapter,
) {
  const newTitleBinding = useVueMvvmProperty(contract.newTitle, adapter);
  const newTitleErrors = useVueMvvmValidation(contract.newTitle, adapter);
  const newNotesBinding = useVueMvvmProperty(contract.newNotes, adapter);
  const newPriorityBinding = useVueMvvmProperty(contract.newPriority, adapter);
  const queryBinding = useVueMvvmProperty(contract.query, adapter);
  const filterBinding = useVueMvvmProperty(contract.filter, adapter);
  const itemsBinding = useVueMvvmCollection(contract.items, adapter);
  const diagnosticsBinding = useVueMvvmCollection(contract.diagnostics, adapter);
  const stateBinding = useVueMvvmProperty(contract.state, adapter);
  const addBinding = useVueMvvmCommandFacade(contract.add, adapter);
  const applyFilterBinding = useVueMvvmCommandFacade(contract.applyFilter, adapter);
  const toggleBinding = useVueMvvmCommandFacade(contract.toggle, adapter);
  const deleteBinding = useVueMvvmCommandFacade(contract.delete, adapter);
  const clearCompletedBinding = useVueMvvmCommandFacade(contract.clearCompleted, adapter);
  const importBinding = useVueMvvmCommandFacade(contract.import, adapter);
  const cancelImportBinding = useVueMvvmCommandFacade(contract.cancelImport, adapter);
  const wizardStartBinding = useVueMvvmCommandFacade(contract.wizardStart, adapter);
  const wizardNextBinding = useVueMvvmCommandFacade(contract.wizardNext, adapter);
  const wizardBackBinding = useVueMvvmCommandFacade(contract.wizardBack, adapter);
  const wizardFinishBinding = useVueMvvmCommandFacade(contract.wizardFinish, adapter);
  const wizardCancelBinding = useVueMvvmCommandFacade(contract.wizardCancel, adapter);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    newNotes: newNotesBinding,
    newPriority: newPriorityBinding,
    query: queryBinding,
    filter: filterBinding,
    items: itemsBinding,
    diagnostics: diagnosticsBinding,
    state: stateBinding,
    add: addBinding,
    applyFilter: applyFilterBinding,
    toggle: toggleBinding,
    delete: deleteBinding,
    clearCompleted: clearCompletedBinding,
    import: importBinding,
    cancelImport: cancelImportBinding,
    wizardStart: wizardStartBinding,
    wizardNext: wizardNextBinding,
    wizardBack: wizardBackBinding,
    wizardFinish: wizardFinishBinding,
    wizardCancel: wizardCancelBinding,
  } as const;
}
