<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>RunicToolkit.Samples.Todo.FrontendHost</AssemblyName>
    <RootNamespace>RunicToolkit.Samples.Todo.FrontendHost</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsWebUi" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <ProjectReference Include="../Todo.Shared/Todo.Shared.csproj" />
    <PackageReference Include="RunicToolkit.Hosting" />
    <PackageReference Include="RunicToolkit.Hosting.Build" PrivateAssets="all" />
    <PackageReference Include="RunicToolkit.Hosting.CsWebUi" />
    <PackageReference Include="RunicToolkit.Hosting.CsWebUi.App" />
    <PackageReference Include="RunicToolkit.Hosting.CsWebUi.Mvvm" />
    <PackageReference Include="RunicToolkit.Hosting.GenericHost" />
    <PackageReference Include="RunicToolkit.Hosting.WebUi" />
    <PackageReference Include="RunicToolkit.MVVM.CommunityToolkit" />
  </ItemGroup>
</Project>
