// <auto-generated />
#nullable enable

namespace WebUIToolkit.Samples.Todo.FrontendHost;

internal static class TodoContracts
{
    internal static class SimpleTodo
    {
        internal const string Name = "samples.todo.simple";

        internal static class Members
        {
            internal const int NewTitle = 1;
            internal const int Items = 3;
            internal const int Add = 10;
            internal const int Toggle = 11;
            internal const int Remove = 12;
        }
    }

    internal static class AdvancedTodo
    {
        internal const string Name = "samples.todo.advanced";

        internal static class Members
        {
            internal const int NewTitle = 1;
            internal const int NewNotes = 2;
            internal const int NewPriority = 3;
            internal const int Query = 4;
            internal const int Filter = 5;
            internal const int Items = 20;
            internal const int Diagnostics = 21;
            internal const int State = 22;
            internal const int Add = 40;
            internal const int ApplyFilter = 41;
            internal const int Toggle = 42;
            internal const int Delete = 43;
            internal const int ClearCompleted = 44;
            internal const int Import = 45;
            internal const int CancelImport = 46;
            internal const int WizardStart = 48;
            internal const int WizardNext = 49;
            internal const int WizardBack = 50;
            internal const int WizardFinish = 51;
            internal const int WizardCancel = 52;
        }
    }

}
