<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>RunicToolkit.Samples.Cwhtml.Components.Tests</AssemblyName>
    <RootNamespace>RunicToolkit.Samples.Cwhtml.Components.Tests</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <DebugType>none</DebugType>
    <EnableDefaultCwhtmlItems>false</EnableDefaultCwhtmlItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../samples/Cwhtml.SampleComponents/RunicToolkit.Samples.Cwhtml.Components.csproj" />
    <PackageReference Include="RunicMarkup" />
    <PackageReference Include="RunicMarkup.Build" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Cwhtml Include="Views/StylingNeutralExample.cwhtml">
      <LogicalPath>Views/StylingNeutralExample.cwhtml</LogicalPath>
    </Cwhtml>
    <CwhtmlCodeBehind Include="StylingNeutralExampleModel.cs" />
  </ItemGroup>

</Project>
