// <auto-generated />
import {
  MvvmCollection,
  MvvmCommand,
  MvvmCommandWithArgument,
  MvvmProperty,
  MvvmReadonlyProperty,
  type MvvmProjection,
} from "@webuitoolkit/mvvm";

export interface SimpleTodoItem {
  readonly id: string;
  readonly title: string;
  readonly isCompleted: boolean;
}

export interface AdvancedTodoItem {
  readonly id: string;
  readonly title: string;
  readonly isCompleted: boolean;
  readonly notes: string;
  readonly priority: "Low" | "Normal" | "High";
  readonly createdAt: string;
  readonly completedAt: string | null;
}

export interface AdvancedTodoState {
  readonly totalCount: number;
  readonly remainingCount: number;
  readonly completedCount: number;
  readonly isImporting: boolean;
  readonly wizardStep: string | null;
  readonly wizardIssues: readonly string[];
}

export interface DiagnosticEntry {
  readonly at: string;
  readonly category: string;
  readonly message: string;
}

export class SimpleTodoContract {
  public static readonly contractName = "samples.todo.simple" as const;
  public static readonly memberMetadata = [
    { id: 1, name: "newTitle", sourceMember: "WebUIToolkit.Samples.SimpleTodo.TodoViewModel.NewTitle" },
    { id: 3, name: "items", sourceMember: "WebUIToolkit.Samples.SimpleTodo.TodoViewModel.Items" },
    { id: 10, name: "add", sourceMember: "WebUIToolkit.Samples.SimpleTodo.TodoViewModel.AddCommand" },
    { id: 11, name: "toggle", sourceMember: "WebUIToolkit.Samples.SimpleTodo.TodoViewModel.ToggleByIdCommand" },
    { id: 12, name: "remove", sourceMember: "WebUIToolkit.Samples.SimpleTodo.TodoViewModel.RemoveByIdCommand" },
  ] as const;

  public readonly newTitle;
  public readonly items;
  public readonly add;
  public readonly toggle;
  public readonly remove;

  public constructor(projection: MvvmProjection) {
    this.newTitle = new MvvmProperty<string>(projection, 1);
    this.items = new MvvmCollection<SimpleTodoItem>(projection, 3);
    this.add = new MvvmCommand(projection, 10);
    this.toggle = new MvvmCommandWithArgument<string>(projection, 11);
    this.remove = new MvvmCommandWithArgument<string>(projection, 12);
  }
}

export class AdvancedTodoContract {
  public static readonly contractName = "samples.todo.advanced" as const;
  public static readonly memberMetadata = [
    { id: 1, name: "newTitle", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.NewTitle" },
    { id: 2, name: "newNotes", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.NewNotes" },
    { id: 3, name: "newPriority", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.NewPriority" },
    { id: 4, name: "query", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.Query" },
    { id: 5, name: "filter", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.Filter" },
    { id: 20, name: "items", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.VisibleItems" },
    { id: 21, name: "diagnostics", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.Diagnostics" },
    { id: 22, name: "state", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.State" },
    { id: 40, name: "add", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.AddCommand" },
    { id: 41, name: "applyFilter", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.ApplyFilterCommand" },
    { id: 42, name: "toggle", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.ToggleByIdCommand" },
    { id: 43, name: "delete", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.DeleteByIdCommand" },
    { id: 44, name: "clearCompleted", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.ClearCompletedCommand" },
    { id: 45, name: "import", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.ImportCommand" },
    { id: 46, name: "cancelImport", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.CancelImportCommand" },
    { id: 48, name: "wizardStart", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.StartWizardCommand" },
    { id: 49, name: "wizardNext", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.WizardNextCommand" },
    { id: 50, name: "wizardBack", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.WizardBackCommand" },
    { id: 51, name: "wizardFinish", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.WizardFinishCommand" },
    { id: 52, name: "wizardCancel", sourceMember: "WebUIToolkit.Samples.AdvancedTodo.UI.TodoViewModel.WizardCancelCommand" },
  ] as const;

  public readonly newTitle;
  public readonly newNotes;
  public readonly newPriority;
  public readonly query;
  public readonly filter;
  public readonly items;
  public readonly diagnostics;
  public readonly state;
  public readonly add;
  public readonly applyFilter;
  public readonly toggle;
  public readonly delete;
  public readonly clearCompleted;
  public readonly import;
  public readonly cancelImport;
  public readonly wizardStart;
  public readonly wizardNext;
  public readonly wizardBack;
  public readonly wizardFinish;
  public readonly wizardCancel;

  public constructor(projection: MvvmProjection) {
    this.newTitle = new MvvmProperty<string>(projection, 1);
    this.newNotes = new MvvmProperty<string>(projection, 2);
    this.newPriority = new MvvmProperty<string>(projection, 3);
    this.query = new MvvmProperty<string>(projection, 4);
    this.filter = new MvvmProperty<string>(projection, 5);
    this.items = new MvvmCollection<AdvancedTodoItem>(projection, 20);
    this.diagnostics = new MvvmCollection<DiagnosticEntry>(projection, 21);
    this.state = new MvvmReadonlyProperty<AdvancedTodoState>(projection, 22);
    this.add = new MvvmCommand(projection, 40);
    this.applyFilter = new MvvmCommand(projection, 41);
    this.toggle = new MvvmCommandWithArgument<string>(projection, 42);
    this.delete = new MvvmCommandWithArgument<string>(projection, 43);
    this.clearCompleted = new MvvmCommand(projection, 44);
    this.import = new MvvmCommand(projection, 45);
    this.cancelImport = new MvvmCommand(projection, 46);
    this.wizardStart = new MvvmCommand(projection, 48);
    this.wizardNext = new MvvmCommand(projection, 49);
    this.wizardBack = new MvvmCommand(projection, 50);
    this.wizardFinish = new MvvmCommand(projection, 51);
    this.wizardCancel = new MvvmCommand(projection, 52);
  }
}
