// <auto-generated />
import {
  MvvmCollection,
  MvvmCommand,
  MvvmCommandWithArgument,
  MvvmProperty,
  MvvmReadonlyProperty,
  type MvvmProjection,
} from "@webuitoolkit/mvvm";

export interface SimpleTodoItem {
  readonly id: string;
  readonly title: string;
  readonly isCompleted: boolean;
}

export interface AdvancedTodoItem {
  readonly id: string;
  readonly title: string;
  readonly isCompleted: boolean;
  readonly notes: string;
  readonly priority: "Low" | "Normal" | "High";
  readonly createdAt: string;
  readonly completedAt: string | null;
}

export interface AdvancedTodoState {
  readonly totalCount: number;
  readonly remainingCount: number;
  readonly completedCount: number;
  readonly isImporting: boolean;
  readonly wizardStep: string | null;
  readonly wizardIssues: readonly string[];
}

export interface DiagnosticEntry {
  readonly at: string;
  readonly category: string;
  readonly message: string;
}

export class SimpleTodoContract {
  public static readonly contractName = "samples.todo.simple" as const;

  public readonly newTitle;
  public readonly items;
  public readonly add;
  public readonly toggle;
  public readonly remove;

  public constructor(projection: MvvmProjection) {
    this.newTitle = new MvvmProperty<string>(projection, 1);
    this.items = new MvvmCollection<SimpleTodoItem>(projection, 3);
    this.add = new MvvmCommand(projection, 10);
    this.toggle = new MvvmCommandWithArgument<string>(projection, 11);
    this.remove = new MvvmCommandWithArgument<string>(projection, 12);
  }
}

export class AdvancedTodoContract {
  public static readonly contractName = "samples.todo.advanced" as const;

  public readonly newTitle;
  public readonly newNotes;
  public readonly newPriority;
  public readonly query;
  public readonly filter;
  public readonly items;
  public readonly diagnostics;
  public readonly state;
  public readonly add;
  public readonly applyFilter;
  public readonly toggle;
  public readonly delete;
  public readonly clearCompleted;
  public readonly import;
  public readonly cancelImport;
  public readonly wizardStart;
  public readonly wizardNext;
  public readonly wizardBack;
  public readonly wizardFinish;
  public readonly wizardCancel;

  public constructor(projection: MvvmProjection) {
    this.newTitle = new MvvmProperty<string>(projection, 1);
    this.newNotes = new MvvmProperty<string>(projection, 2);
    this.newPriority = new MvvmProperty<string>(projection, 3);
    this.query = new MvvmProperty<string>(projection, 4);
    this.filter = new MvvmProperty<string>(projection, 5);
    this.items = new MvvmCollection<AdvancedTodoItem>(projection, 20);
    this.diagnostics = new MvvmCollection<DiagnosticEntry>(projection, 21);
    this.state = new MvvmReadonlyProperty<AdvancedTodoState>(projection, 22);
    this.add = new MvvmCommand(projection, 40);
    this.applyFilter = new MvvmCommand(projection, 41);
    this.toggle = new MvvmCommandWithArgument<string>(projection, 42);
    this.delete = new MvvmCommandWithArgument<string>(projection, 43);
    this.clearCompleted = new MvvmCommand(projection, 44);
    this.import = new MvvmCommand(projection, 45);
    this.cancelImport = new MvvmCommand(projection, 46);
    this.wizardStart = new MvvmCommand(projection, 48);
    this.wizardNext = new MvvmCommand(projection, 49);
    this.wizardBack = new MvvmCommand(projection, 50);
    this.wizardFinish = new MvvmCommand(projection, 51);
    this.wizardCancel = new MvvmCommand(projection, 52);
  }
}
