#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { execFile as execute } from 'node:child_process';
import { cp, mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import { pathToFileURL } from 'node:url';

const root = resolve(import.meta.dirname, '../..');
const schema = 'runic.local-documentation-support-parity/1';
const repeatSchema = 'runic.local-documentation-support-parity-repeat/1';
const profiles = ['csharp-host', 'local-application-bridge', 'editor-desktop', 'd008-hosted-product'];
const claimEvidence = [['csharp-host', 'w70-clean-room'], ['local-application-bridge', 'w70-clean-room'], ['editor-interchange', 'w70-clean-room'], ['hosted-locale', 'w70-clean-room'], ['support-envelope', 'w70-support'], ['manual-replacement', 'w60-preflight'], ['recovery', 'w70-support'], ['native-refusal', 'w70-native']];
const privacy = ['source-content', 'translation-content', 'review-content', 'session-content', 'cookie-content', 'token-content'];
const same = (left, right) => JSON.stringify(left) === JSON.stringify(right);
const sha256 = (value) => createHash('sha256').update(value).digest('hex');
const execFile = promisify(execute);
const fail = (message) => { throw new Error(`documentation support parity: ${message}`); };
const zero = (value, keys) => same(value, Object.fromEntries(keys.map((key) => [key, 0])));

async function input(path, name) { const bytes = await readFile(resolve(path)); try { return { sha256: sha256(bytes), value: JSON.parse(bytes) }; } catch { fail(`${name} must be valid JSON`); } }
function repeated(value, journeySchema, name) { const repeatedSchema = journeySchema.replace(/\/1$/, '-repeat/1'); if (value?.schema !== repeatedSchema || !Array.isArray(value.journeys) || value.journeys.length !== 2 || !same(value.journeys[0], value.journeys[1]) || value.journeys[0]?.schema !== journeySchema) fail(`${name} is not a deterministic ${journeySchema} receipt`); return value.journeys[0]; }
function audit(value) { const journey = repeated(value, 'runic.local-nonpublic-readiness-audit/1', 'W80 audit'); if (journey.publication !== 'forbidden' || !same(Object.keys(journey.retainedProfiles ?? {}).sort(), [...profiles].sort()) || !same(journey.isolation, { inputs: 'isolated-copy', transport: 'none' }) || journey.postFreezePackageGate?.status !== 'passed-not-retained' || !same(journey.nativeCapability, { status: 'unavailable', capability: 'private-file-handler-streaming-unavailable', abiOracle: 'passing' }) || !zero(journey.externalActions, ['requests', 'signatures', 'updates', 'uploads', 'releases', 'tags'])) fail('W80 audit is not the closed local non-public readiness boundary'); return journey; }
function receiptLink(value, journeySchema, name, auditItem, actual) { const journey = repeated(value, journeySchema, name); if (actual.sha256 !== auditItem?.sha256 || actual.value.schema !== auditItem?.schema) fail(`${name} does not match the W80 audit evidence`); return journey; }
export function claimManifest(value) { const native = value?.claims?.find((item) => item.id === 'native-refusal'); if (value?.schema !== 'runic.local-nonpublic-documentation-claims/1' || value.publication !== 'forbidden' || !same(value.profiles, profiles) || !same(value.claims?.map((item) => [item.id, item.evidence]), claimEvidence) || new Set(value.claims.map((item) => item.anchor)).size !== value.claims.length || value.claims.some((item) => !/^[a-z][a-z-]*$/.test(item.anchor ?? '') || typeof item.text !== 'string' || /\b(published version|signed artifact|automatic update|download now)\b/i.test(item.text)) || !/managed refusal/i.test(native?.text ?? '') || !/not (?:browser or )?native platform success/i.test(native?.text ?? '') || !privacy.every((item) => value.nonClaims?.includes(item)) || ['version-assignment', 'publication', 'signing', 'notarization', 'upload', 'updates', 'telemetry'].some((item) => !value.nonClaims?.includes(item))) fail('documentation claims are uncited, contradictory, publishing, updater, or privacy-leaking'); return value; }
function citation(auditJourney, id) { const items = auditJourney.evidence?.w70Freeze?.citations?.filter((item) => item.id === id); if (items?.length !== 1) fail(`W80 audit lacks exactly one ${id} citation`); return items[0]; }
export function renderedProjection(html, claims) { if (!html.includes('Four retained profiles, no public-release promise.') || /\b(Published distribution|automatic update)\b/i.test(html) || claims.claims.some((item) => !html.includes(`id="${item.anchor}"`) || !html.includes(item.text))) fail('rendered readiness page has a contradictory or unresolved claim'); return { heading: 'Four retained profiles, no public-release promise.', claims: claims.claims.map(({ anchor, text }) => ({ anchor, text })) }; }
async function build(docsRoot, authorityRoot, out) { try { await execFile('npm', ['run', 'build'], { cwd: docsRoot, env: { ...process.env, NO_PROXY: '*', npm_config_audit: 'false', npm_config_fund: 'false', RUNIC_DOCS_BUILD_OUTPUT: out, RUNIC_RELEASE_MANIFEST: join(authorityRoot, 'runic.release.json'), RUNIC_RELEASE_AUTHORITY_REVISION: '6ef82b10963bdda4b827b82ae94bb56da0ab5103' } }); } catch (error) { fail(`documentation build failed: ${String(error.stderr ?? error.message).slice(-512)}`); } }
async function source(docsRoot) { const [status, revision, tree] = await Promise.all([execFile('git', ['status', '--porcelain'], { cwd: docsRoot }), execFile('git', ['rev-parse', 'HEAD'], { cwd: docsRoot }), execFile('git', ['rev-parse', 'HEAD^{tree}'], { cwd: docsRoot })]); if (status.stdout !== '') fail('documentation source must be clean'); return { repository: 'https://github.com/Runic-Artifex/runic-docs', revision: revision.stdout.trim(), tree: tree.stdout.trim() }; }
async function authority(authorityRoot) { const [status, revision, tree, manifest] = await Promise.all([execFile('git', ['status', '--porcelain'], { cwd: authorityRoot }), execFile('git', ['rev-parse', 'HEAD'], { cwd: authorityRoot }), execFile('git', ['rev-parse', 'HEAD^{tree}'], { cwd: authorityRoot }), readFile(join(authorityRoot, 'runic.release.json'))]); if (status.stdout !== '' || revision.stdout.trim() !== '6ef82b10963bdda4b827b82ae94bb56da0ab5103' || tree.stdout.trim() !== '12d1e735adedb5b6ec38fe5af09d7934a4e8925c') fail('documentation authority is not the pinned clean W04 source'); return { revision: revision.stdout.trim(), tree: tree.stdout.trim(), manifestSha256: sha256(manifest) }; }
async function verifiers() { return { audit: await import(pathToFileURL(join(root, 'eng/current-readiness-audit/verify.mjs')).href), clean: await import(pathToFileURL(join(root, 'eng/current-controlled-clean-room/verify.mjs')).href), support: await import(pathToFileURL(join(root, 'eng/current-support-certification/verify.mjs')).href), native: await import(pathToFileURL(join(root, 'eng/current-native-shell-certification/verify.mjs')).href) }; }
function check(report, name) { if (!report?.ok) fail(`${name} verifier rejected its receipt: ${(report.errors ?? []).join('; ')}`); }

async function collect(paths) {
  const docsRoot = resolve(paths['docs-root']), authorityRoot = resolve(paths.authority); const [claimsInput, auditInput, cleanInput, supportInput, nativeInput, authorityFacts] = await Promise.all([input(paths.claims, 'claims'), input(paths.audit, 'audit'), input(paths['clean-room'], 'clean room'), input(paths.support, 'support'), input(paths.native, 'native'), authority(authorityRoot)]);
  const claims = claimManifest(claimsInput.value), readiness = audit(auditInput.value), checks = await verifiers(); check(checks.audit.verifyReceipt(auditInput.value, readiness), 'W80 audit');
  const clean = receiptLink(cleanInput.value, 'runic.controlled-clean-room-conformance/1', 'clean room', readiness.evidence?.w70CleanRoom, cleanInput), support = receiptLink(supportInput.value, 'runic.support-certification/1', 'support', readiness.evidence?.w70Support, supportInput), native = receiptLink(nativeInput.value, 'runic.native-shell-capability-certification/1', 'native', readiness.evidence?.w70Native, nativeInput);
  check(checks.clean.verifyReceipt(cleanInput.value, clean), 'clean room'); check(checks.support.verifyReceipt(supportInput.value, support), 'support'); check(checks.native.verifyReceipt(nativeInput.value, native), 'native');
  if (!same(clean.frozenProfile?.profiles, readiness.retainedProfiles) || !same(support.frozenProfile?.profiles, readiness.retainedProfiles) || !same(native.frozenProfile?.profiles, readiness.retainedProfiles) || citation(readiness, 'w60-preflight').profile !== 'editor-desktop' || native.observedProfile?.certifiedResult?.status !== 'unavailable' || native.observedProfile?.certifiedResult?.capability !== 'private-file-handler-streaming-unavailable' || !same(support.privacy, { optIn: true, excluded: ['source', 'translation', 'review', 'session', 'cookie', 'token'], outboundTransportAttempts: 0, upload: 'forbidden', telemetry: 'forbidden' }) || !same(support.recovery, { completeRollback: true, mutationBeforeRecovery: 'rejected', staleBridgeState: 'rejected', diagnostics: 'sanitized-counts' })) fail('support, recovery, manual replacement, or managed-refusal evidence was softened');
  const out = await mkdtemp(join(tmpdir(), 'runic-w80-docs-build-')); try { await build(docsRoot, authorityRoot, out); const html = await readFile(join(out, 'readiness/index.html'), 'utf8'), renderedClaims = renderedProjection(html, claims); return { schema, publication: 'forbidden', isolation: { evidenceInputs: 'isolated-copy', documentationBuild: 'fresh-temporary-output', transport: 'none' }, documentation: { source: await source(docsRoot), authority: authorityFacts, claims: { sha256: claimsInput.sha256, schema: claims.schema }, readinessPage: { path: '/readiness', semanticSha256: sha256(JSON.stringify(renderedClaims)) } }, evidence: { audit: { sha256: auditInput.sha256, schema: auditInput.value.schema }, cleanRoom: { sha256: cleanInput.sha256, schema: cleanInput.value.schema }, support: { sha256: supportInput.sha256, schema: supportInput.value.schema }, native: { sha256: nativeInput.sha256, schema: nativeInput.value.schema }, manualReplacement: { sha256: citation(readiness, 'w60-preflight').sha256, schema: citation(readiness, 'w60-preflight').schema } }, nonClaims: claims.nonClaims, nativeCapability: readiness.nativeCapability, externalActions: { requests: 0, uploads: 0, publications: 0, signatures: 0, updates: 0, telemetry: 0 } }; } finally { await rm(out, { recursive: true, force: true }); }
}
export function verifyReceipt(value, expected) { const errors = []; if (value?.schema !== repeatSchema || !Array.isArray(value.journeys) || value.journeys.length !== 2 || !same(value.journeys?.[0], value.journeys?.[1])) errors.push('two deterministic documentation parity journeys are required'); if (expected && !same(value?.journeys?.[0], expected)) errors.push('receipt differs from exact local inputs'); for (const journey of value?.journeys ?? []) if (journey?.schema !== schema || journey.publication !== 'forbidden' || !same(journey.isolation, { evidenceInputs: 'isolated-copy', documentationBuild: 'fresh-temporary-output', transport: 'none' }) || journey.documentation?.authority?.revision !== '6ef82b10963bdda4b827b82ae94bb56da0ab5103' || journey.documentation?.authority?.tree !== '12d1e735adedb5b6ec38fe5af09d7934a4e8925c' || !/^[a-f0-9]{64}$/.test(journey.documentation?.authority?.manifestSha256 ?? '') || journey.documentation?.readinessPage?.path !== '/readiness' || !/^[a-f0-9]{64}$/.test(journey.documentation?.readinessPage?.semanticSha256 ?? '') || !privacy.every((item) => journey.nonClaims?.includes(item)) || !same(journey.nativeCapability, { status: 'unavailable', capability: 'private-file-handler-streaming-unavailable', abiOracle: 'passing' }) || !zero(journey.externalActions, ['requests', 'uploads', 'publications', 'signatures', 'updates', 'telemetry'])) errors.push('documentation parity boundary mismatch'); return { ok: errors.length === 0, errors }; }
async function isolated(paths) { const directory = await mkdtemp(join(tmpdir(), 'runic-w80-docs-evidence-')); try { const copied = { 'docs-root': paths['docs-root'], authority: paths.authority }; for (const name of ['claims', 'audit', 'clean-room', 'support', 'native']) { copied[name] = join(directory, `${name}.json`); await cp(resolve(paths[name]), copied[name]); } return await collect(copied); } finally { await rm(directory, { recursive: true, force: true }); } }
export async function runTwice(paths) { const value = { schema: repeatSchema, journeys: [await isolated(paths), await isolated(paths)] }; const report = verifyReceipt(value); if (!report.ok) fail(report.errors.join('; ')); return value; }
function args(argv) { const values = {}; for (let index = 0; index < argv.length; index += 2) { if (!argv[index]?.startsWith('--') || !argv[index + 1] || values[argv[index]]) fail('usage'); values[argv[index].slice(2)] = argv[index + 1]; } const names = ['docs-root', 'authority', 'claims', 'audit', 'clean-room', 'support', 'native']; if (!same(Object.keys(values).filter((name) => name !== 'receipt').sort(), names.sort())) fail('all documentation parity inputs are required'); return values; }
async function main(argv) { const [command, ...rest] = argv, options = args(rest); if (command === 'run-twice' && !options.receipt) return JSON.stringify(await runTwice(options), null, 2); if (command === 'verify-twice' && options.receipt) { const actual = JSON.parse(await readFile(options.receipt)); const expected = await runTwice(options), report = verifyReceipt(actual, expected.journeys[0]); if (!report.ok || !same(actual, expected)) fail(report.errors.concat('receipt differs from exact local inputs').join('; ')); return; } fail('usage'); }
if (import.meta.main) main(process.argv.slice(2)).then((output) => { if (output) process.stdout.write(`${output}\n`); }).catch((error) => { process.stderr.write(`${error.message}\n`); process.exitCode = 1; });
