import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { claimManifest, renderedProjection, verifyReceipt } from './verify.mjs';

const journey = () => ({ schema: 'runic.local-documentation-support-parity/1', publication: 'forbidden', isolation: { evidenceInputs: 'isolated-copy', documentationBuild: 'fresh-temporary-output', transport: 'none' }, documentation: { authority: { revision: '6ef82b10963bdda4b827b82ae94bb56da0ab5103', tree: '12d1e735adedb5b6ec38fe5af09d7934a4e8925c', manifestSha256: 'b'.repeat(64) }, readinessPage: { path: '/readiness', semanticSha256: 'a'.repeat(64) } }, nonClaims: ['source-content', 'translation-content', 'review-content', 'session-content', 'cookie-content', 'token-content'], nativeCapability: { status: 'unavailable', capability: 'private-file-handler-streaming-unavailable', abiOracle: 'passing' }, externalActions: { requests: 0, uploads: 0, publications: 0, signatures: 0, updates: 0, telemetry: 0 } });
test('accepts deterministic local documentation parity', () => { const value = journey(); assert.deepEqual(verifyReceipt({ schema: 'runic.local-documentation-support-parity-repeat/1', journeys: [value, structuredClone(value)] }, value), { ok: true, errors: [] }); });
test('rejects publishing, privacy, and native-success drift', () => { const first = journey(), second = journey(); second.publication = 'published'; second.nonClaims.pop(); second.nativeCapability.status = 'available'; const report = verifyReceipt({ schema: 'runic.local-documentation-support-parity-repeat/1', journeys: [first, second] }, first); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /two deterministic|documentation parity/); });
test('permits the explicit native refusal but rejects softened or affirmative claim wording', () => { const value = JSON.parse(readFileSync(new URL('../../../runic-docs/src/lib/local-readiness-claims.json', import.meta.url))); assert.equal(claimManifest(value), value); const softened = structuredClone(value); softened.claims.find((item) => item.id === 'native-refusal').text = 'Linux/X64 has a managed native boundary.'; assert.throws(() => claimManifest(softened), /documentation claims/); const published = structuredClone(value); published.claims.find((item) => item.id === 'support-envelope').text = 'An automatic update is available now.'; assert.throws(() => claimManifest(published), /documentation claims/); });
test('tolerates bundle filenames only after raw claims and anchors validate', () => { const claims = claimManifest(JSON.parse(readFileSync(new URL('../../../runic-docs/src/lib/local-readiness-claims.json', import.meta.url)))); const body = `<h1>Four retained profiles, no public-release promise.</h1>${claims.claims.map((item) => `<section id="${item.anchor}">${item.text}</section>`).join('')}`; assert.deepEqual(renderedProjection(`${body}<script src="/_app/immutable/chunks/one.js"></script>`, claims), renderedProjection(`${body}<script src="/_app/immutable/chunks/two.js"></script>`, claims)); assert.throws(() => renderedProjection(body.replace(claims.claims[0].text, 'changed claim'), claims), /rendered readiness page/); });
