#!/usr/bin/env node
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const executable = process.env.RUNIC_W60_EDITOR_EXECUTABLE && resolve(process.env.RUNIC_W60_EDITOR_EXECUTABLE);
const candidates = process.env.RUNIC_W60_EDITOR_CANDIDATES && resolve(process.env.RUNIC_W60_EDITOR_CANDIDATES);
const authority = process.env.RUNIC_W60_AUTHORITY_MANIFEST && resolve(process.env.RUNIC_W60_AUTHORITY_MANIFEST);
const candidateReceipt = process.env.RUNIC_W60_CANDIDATE_RECEIPT && resolve(process.env.RUNIC_W60_CANDIDATE_RECEIPT);
const schema = "runic.manual-replacement-preflight-consumer/1", repeatSchema = "runic.manual-replacement-preflight-consumer-repeat/1";
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const hash = async path => createHash("sha256").update(await readFile(path)).digest("hex");
const run = (args, cwd) => new Promise(done => { const child = spawn("dotnet", [executable, "manual-replacement-preflight", ...args], { cwd, stdio: ["ignore", "pipe", "pipe"] }); const output=[]; child.stdout.on("data", x=>output.push(x)); child.stderr.on("data", x=>output.push(x)); child.on("close", exitCode=>done({exitCode, output:Buffer.concat(output).toString("utf8")})); child.on("error", error=>done({exitCode:null,output:String(error)})); });
const args = (root, replacement, receipt = candidateReceipt) => ["--current-archive", join(root,"linux-x64","RunicTranslations.Editor-0.1.0-preview.contract-linux-x64.tar.gz"), "--current-staging", join(root,"linux-x64","release-staging"), "--replacement-archive", join(replacement,"linux-x64","RunicTranslations.Editor-0.1.0-preview.contract-linux-x64.tar.gz"), "--replacement-staging", join(replacement,"linux-x64","release-staging"), "--authority", authority, "--candidate-receipt", receipt];
const response = async (input, cwd) => { const result = await run(input, cwd); if (result.exitCode !== 0) throw new Error(result.output); return JSON.parse(result.output); };

export function verifyReceipt(receipt, expected) { const errors=[]; if(receipt?.schema!==repeatSchema||receipt?.journeys?.length!==2) errors.push("two journeys required"); for(const journey of receipt?.journeys??[]) { if(journey?.schema!==schema||journey?.result!=="manual-replacement-eligible"||journey?.networkAttempts!==0||journey?.processMutations!==0||journey?.guidance!=="user-performed-verified-manual-replacement"||!same(journey?.hostileDiagnostics,["RID-MISMATCH","ARCHIVE-RECEIPT-MISMATCH","CANDIDATE-MODEL-STALE","CANDIDATE-PLATFORM-MISMATCH"])) errors.push("preflight evidence mismatch"); if(expected&&!same(journey?.provenance,expected)) errors.push("candidate provenance mismatch"); } if(receipt?.journeys?.length===2&&!same(receipt.journeys[0],receipt.journeys[1]))errors.push("journeys not deterministic"); return {ok:errors.length===0,errors}; }
async function one() { if(!executable||!candidates||!authority||!candidateReceipt) throw new Error("RUNIC_W60_EDITOR_EXECUTABLE, RUNIC_W60_EDITOR_CANDIDATES, RUNIC_W60_AUTHORITY_MANIFEST, and RUNIC_W60_CANDIDATE_RECEIPT are required."); const dir=await mkdtemp(join(tmpdir(),"runic-w60-manual-replacement-")); try { const current=join(dir,"current"), replacement=join(dir,"replacement"), stale=join(dir,"stale.json"), forged=join(dir,"forged-platform.json"); await cp(candidates,current,{recursive:true}); await cp(candidates,replacement,{recursive:true}); const good=await response(args(current,replacement),dir); if(good.result!=="manual-replacement-eligible"||!good.guidance?.includes("perform the replacement yourself")||/update|download|install|delete|rollback/i.test(good.guidance.replace("does not replace, install, delete, download, or roll back anything.",""))) throw new Error("positive guidance is unsafe"); const rid=await response(["--current-archive",join(current,"linux-x64","RunicTranslations.Editor-0.1.0-preview.contract-linux-x64.tar.gz"),"--current-staging",join(current,"linux-x64","release-staging"),"--replacement-archive",join(replacement,"win-x64","RunicTranslations.Editor-0.1.0-preview.contract-win-x64.zip"),"--replacement-staging",join(replacement,"win-x64","release-staging"),"--authority",authority,"--candidate-receipt",candidateReceipt],dir); await writeFile(join(replacement,"linux-x64","RunicTranslations.Editor-0.1.0-preview.contract-linux-x64.tar.gz"),"forged"); const tampered=await response(args(current,replacement),dir); const receiptText=await readFile(candidateReceipt,"utf8"); await writeFile(stale,receiptText.replace(/"sha256":\s*"[a-f0-9]{64}"/,`"sha256":"${"f".repeat(64)}"`)); const staleResult=await response(args(current,current,stale),dir); const forgedReceipt=JSON.parse(receiptText); for(const journey of forgedReceipt.journeys) journey.candidateSet.platforms[0].source.revision="f".repeat(40); await writeFile(forged,JSON.stringify(forgedReceipt)); const forgedResult=await response(args(current,current,forged),dir); if(rid.diagnostics?.[0]!=="RID-MISMATCH"||tampered.diagnostics?.[0]!=="ARCHIVE-RECEIPT-MISMATCH"||staleResult.diagnostics?.[0]!=="CANDIDATE-MODEL-STALE"||forgedResult.diagnostics?.[0]!=="CANDIDATE-PLATFORM-MISMATCH") throw new Error("hostile preflight did not fail closed"); const provenance={ executable:{sha256:await hash(executable)}, candidateReceipt:{sha256:await hash(candidateReceipt)}, authority:{sha256:await hash(authority)} }; return {schema,result:good.result,guidance:"user-performed-verified-manual-replacement",networkAttempts:0,processMutations:0,hostileDiagnostics:["RID-MISMATCH","ARCHIVE-RECEIPT-MISMATCH","CANDIDATE-MODEL-STALE","CANDIDATE-PLATFORM-MISMATCH"],provenance}; } finally { await rm(dir,{recursive:true,force:true}); } }
export async function runTwice(){const first=await one(),second=await one(),receipt={schema:repeatSchema,journeys:[first,second]},report=verifyReceipt(receipt,first.provenance);if(!report.ok)throw new Error(report.errors.join("\n"));return receipt;}
if(import.meta.main){const [command,path]=process.argv.slice(2);if(command==="run-twice")process.stdout.write(JSON.stringify(await runTwice(),null,2)+"\n");else if(command==="verify-twice"&&path){const expected=(await one()).provenance,report=verifyReceipt(JSON.parse(await readFile(path,"utf8")),expected);if(!report.ok)throw new Error(report.errors.join("\n"));}else throw new Error("Usage: verify.mjs run-twice | verify-twice <receipt>");}
