import assert from 'node:assert/strict';
import test from 'node:test';
import { BRIDGE_CONTRACT, CANDIDATE_NAMES, NPM_FEED, RECEIPT_SCHEMA, REPEAT_RECEIPT_SCHEMA, verifyReceipt, verifyRepeatedReceipt } from './verify.mjs';

const authority = { path: 'runic.release.json', revision: 'a'.repeat(40), tree: 'b'.repeat(40), digest: 'c'.repeat(64), publicPackageCounts: { nuget: 1, npm: 1 }, before: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' }, after: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' } };
const phase = (name, argv) => ({ name, argv, status: 'passed', exitCode: 0, reasonCode: null });
function receipt() { return { schema: RECEIPT_SCHEMA, feeds: { npm: NPM_FEED }, isolation: { npmCache: '.npm-cache' }, releaseManifest: structuredClone(authority), bridgeContract: structuredClone(BRIDGE_CONTRACT), bridgeManifestSha256: 'a'.repeat(64), candidates: CANDIDATE_NAMES.map((identity) => ({ identity, version: '0.2.0', source: NPM_FEED, integrity: 'sha512-fixture', archiveSha256: 'b'.repeat(64) })), phases: [phase('generated-contract', ['node', '<authoritative-generator>', 'check', '--source', 'current-host-transport/application.bridge.ts', '--ir', 'current-host-transport/generated/bridge.ir.json', '--facade', 'current-host-transport/generated/application.bridge.generated.ts']), phase('npm-install', ['npm', 'install', '--ignore-scripts']), phase('angular-controller', ['node', 'consumer.mjs', 'generated/bridge.ir.json', BRIDGE_CONTRACT.fingerprint])] }; }
test('Angular controller receipt accepts shared generated-contract provenance', () => assert.deepEqual(verifyReceipt(receipt(), authority), { ok: true, errors: [] }));
test('Angular controller receipt rejects forged identity and package provenance', () => { const value = receipt(); value.bridgeContract.fingerprint = 'forged'; value.candidates[1].source = 'public'; const report = verifyReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /shared generated contract|npm provenance/); });
test('Angular controller repeat receipt requires identical journeys', () => { const value = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [receipt(), receipt()] }; assert.deepEqual(verifyRepeatedReceipt(value, authority), { ok: true, errors: [] }); value.journeys[1].phases[2].status = 'failed'; const report = verifyRepeatedReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /angular-controller|not deterministic/); });
