<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WebUIToolkit.ReferenceApplication</AssemblyName>
    <RootNamespace>WebUIToolkit.ReferenceApplication</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <IsPackable>false</IsPackable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CA1812</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WebUIToolkit.Hosting.GenericHost" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.Hosting.WebUi" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.MVVM" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.MVVM.Flow" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.TextResources" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.CommandLine" Version="[1.0.0]" />
    <PackageReference Include="WebUIToolkit.DependencyNotices.Runtime" Version="[1.0.0]" />
  </ItemGroup>
</Project>
