// <auto-generated />
import {
  useMvvmCollection,
  useMvvmCommandFacade,
  useMvvmProperty,
  useMvvmValidation,
} from "@webuitoolkit/mvvm-react";
import type { SimpleTodoContract, AdvancedTodoContract } from "../../shared/todo-contract.g.js";

export function useSimpleTodoBindings(contract: SimpleTodoContract) {
  const newTitleBinding = useMvvmProperty(contract.newTitle);
  const newTitleErrors = useMvvmValidation(contract.newTitle);
  const itemsBinding = useMvvmCollection(contract.items);
  const addBinding = useMvvmCommandFacade(contract.add);
  const toggleBinding = useMvvmCommandFacade(contract.toggle);
  const removeBinding = useMvvmCommandFacade(contract.remove);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    items: itemsBinding,
    add: addBinding,
    toggle: toggleBinding,
    remove: removeBinding,
  } as const;
}

export function useAdvancedTodoBindings(contract: AdvancedTodoContract) {
  const newTitleBinding = useMvvmProperty(contract.newTitle);
  const newTitleErrors = useMvvmValidation(contract.newTitle);
  const newNotesBinding = useMvvmProperty(contract.newNotes);
  const newPriorityBinding = useMvvmProperty(contract.newPriority);
  const queryBinding = useMvvmProperty(contract.query);
  const filterBinding = useMvvmProperty(contract.filter);
  const itemsBinding = useMvvmCollection(contract.items);
  const diagnosticsBinding = useMvvmCollection(contract.diagnostics);
  const stateBinding = useMvvmProperty(contract.state);
  const addBinding = useMvvmCommandFacade(contract.add);
  const applyFilterBinding = useMvvmCommandFacade(contract.applyFilter);
  const toggleBinding = useMvvmCommandFacade(contract.toggle);
  const deleteBinding = useMvvmCommandFacade(contract.delete);
  const clearCompletedBinding = useMvvmCommandFacade(contract.clearCompleted);
  const importBinding = useMvvmCommandFacade(contract.import);
  const cancelImportBinding = useMvvmCommandFacade(contract.cancelImport);
  const wizardStartBinding = useMvvmCommandFacade(contract.wizardStart);
  const wizardNextBinding = useMvvmCommandFacade(contract.wizardNext);
  const wizardBackBinding = useMvvmCommandFacade(contract.wizardBack);
  const wizardFinishBinding = useMvvmCommandFacade(contract.wizardFinish);
  const wizardCancelBinding = useMvvmCommandFacade(contract.wizardCancel);
  return {
    contract,
    newTitle: newTitleBinding,
    newTitleErrors,
    newNotes: newNotesBinding,
    newPriority: newPriorityBinding,
    query: queryBinding,
    filter: filterBinding,
    items: itemsBinding,
    diagnostics: diagnosticsBinding,
    state: stateBinding,
    add: addBinding,
    applyFilter: applyFilterBinding,
    toggle: toggleBinding,
    delete: deleteBinding,
    clearCompleted: clearCompletedBinding,
    import: importBinding,
    cancelImport: cancelImportBinding,
    wizardStart: wizardStartBinding,
    wizardNext: wizardNextBinding,
    wizardBack: wizardBackBinding,
    wizardFinish: wizardFinishBinding,
    wizardCancel: wizardCancelBinding,
  } as const;
}
