import assert from 'node:assert/strict';
import test from 'node:test';
import { CANDIDATE, DECLARATION, DECLARATION_SHA256, FEED, RECEIPT_SCHEMA, REPEAT_RECEIPT_SCHEMA, verifyReceipt, verifyRepeatedReceipt } from './verify.mjs';

const phase = (name, argv) => ({ name, argv, status: 'passed', exitCode: 0, reasonCode: null });
function receipt() { return { schema: RECEIPT_SCHEMA, feed: FEED, isolation: { nugetGlobalPackagesFolder: '.nuget/packages', dotnetCliHome: '.dotnet' }, declaration: structuredClone(DECLARATION), declarationSha256: DECLARATION_SHA256, candidate: { ...CANDIDATE, source: FEED, contentHash: 'sha512-fixture' }, servicePolicy: structuredClone(DECLARATION), phases: [phase('restore', ['dotnet', 'restore', 'ServiceDeclaration.csproj', '--configfile', 'NuGet.config', '--no-cache', '--force-evaluate', '--nologo']), phase('build', ['dotnet', 'build', 'ServiceDeclaration.csproj', '--no-restore', '--configuration', 'Release', '--nologo']), phase('run', ['dotnet', 'run', '--project', 'ServiceDeclaration.csproj', '--no-build', '--configuration', 'Release'])] }; }

test('service declaration receipt accepts the C# cookie and proxy policy', () => assert.deepEqual(verifyReceipt(receipt()), { ok: true, errors: [] }));
test('service declaration receipt rejects missing or forged policy inputs', () => { const missing = receipt(); delete missing.declaration.authentication; const forged = receipt(); forged.declaration.authentication.carrier = 'bearer-token'; forged.declaration.ownership.serviceIdentitySessionEndpointPolicy = 'frontend'; for (const value of [missing, forged]) { const report = verifyReceipt(value); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /authentication carrier|C# ownership/); } });
test('service declaration repeat receipt requires byte-identical journeys', () => { const value = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [receipt(), receipt()] }; assert.deepEqual(verifyRepeatedReceipt(value), { ok: true, errors: [] }); value.journeys[1].candidate.contentHash = 'forged'; const report = verifyRepeatedReceipt(value); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /not deterministic/); });
