<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicToolkitDefaultTargetFramework)</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RunicCommandLine.Abstractions" />
    <PackageReference Include="RunicCommandLine" />
  </ItemGroup>
</Project>
