import assert from 'node:assert/strict';
import test from 'node:test';
import { CANDIDATE_FEED_PATH, NPM_CANDIDATE_NAMES, NUGET_CANDIDATES, NUGET_FEED, NPM_FEED, RECEIPT_SCHEMA, REPEAT_RECEIPT_SCHEMA, requireCandidateFeed, verifyReceipt, verifyRepeatedReceipt } from './verify.mjs';

const authority = { path: 'runic.release.json', revision: 'a'.repeat(40), tree: 'b'.repeat(40), digest: 'c'.repeat(64), publicPackageCounts: { nuget: 1, npm: 1 }, before: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' }, after: { revision: 'a'.repeat(40), tree: 'b'.repeat(40), status: '' } };
const phase = (name, argv) => ({ name, argv, status: 'passed', exitCode: 0, reasonCode: null });
function receipt() { const version = NUGET_CANDIDATES[0].version; return { schema: RECEIPT_SCHEMA, feeds: { nuget: NUGET_FEED, npm: NPM_FEED }, isolation: { nugetGlobalPackagesFolder: '.nuget/packages', nugetHttpCachePath: '.nuget/http-cache', dotnetCliHome: '.dotnet', npmCache: '.npm-cache' }, releaseManifest: structuredClone(authority), template: { identity: 'runic-app-svelte', version, assetsVersion: NUGET_CANDIDATES[4].version }, manifest: { schema: 'runic.application/1', provenance: 'template' }, bridgeManifest: { protocol: 'runic.artifex.counter', version: 1, fingerprint: 'fixture' }, nugetCandidates: NUGET_CANDIDATES.map((candidate) => ({ ...candidate, source: NUGET_FEED, contentHash: 'fixture' })), npmCandidates: NPM_CANDIDATE_NAMES.map((identity) => ({ identity, version: '0.1.0', source: NPM_FEED, integrity: 'sha512-fixture', archiveSha256: 'd'.repeat(64) })), phases: [phase('template-install', ['dotnet', 'new', 'install', `Runic.Application.Templates::${version}`, '--nuget-source', CANDIDATE_FEED_PATH]), phase('template-create', ['dotnet', 'new', 'runic-app-svelte', '--name', 'CurrentSvelteTemplate', '--output', 'CurrentSvelteTemplate', '--runicApplicationVersion', version, '--runicAssetsVersion', NUGET_CANDIDATES[4].version]), phase('npm-install', ['npm', 'install', '--ignore-scripts']), phase('frontend-build', ['npm', 'run', 'build']), phase('restore', ['dotnet', 'restore', 'CurrentSvelteTemplate.csproj', '--configfile', 'NuGet.config', '--no-cache', '--force-evaluate', '--nologo']), phase('build', ['dotnet', 'build', 'CurrentSvelteTemplate.csproj', '--no-restore', '--configuration', 'Release', '--nologo']), phase('smoke', ['dotnet', 'run', '--project', 'CurrentSvelteTemplate.csproj', '--no-build', '--configuration', 'Release', '--', '--smoke-test']), phase('tool-install', ['dotnet', 'tool', 'install', 'dotnet-runic', '--tool-path', '../.tools', '--version', version, '--configfile', '../NuGet.config', '--no-cache']), phase('inspect-first', ['dotnet-runic', 'inspect', '--project', 'CurrentSvelteTemplate.csproj', '--configuration', 'Release']), phase('inspect-second', ['dotnet-runic', 'inspect', '--project', 'CurrentSvelteTemplate.csproj', '--configuration', 'Release'])] }; }
test('Svelte template requires an explicit isolated candidate feed', () => assert.throws(() => requireCandidateFeed(undefined), /RUNIC_CURRENT_SVELTE_TEMPLATE_NUGET_FEED/));
test('Svelte template receipt accepts exact isolated candidate evidence', () => assert.deepEqual(verifyReceipt(receipt(), authority), { ok: true, errors: [] }));
test('Svelte template receipt rejects forged feed, manifest, and npm provenance', () => { const value = receipt(); value.feeds.npm = 'public'; value.manifest.provenance = 'unknown'; value.npmCandidates[0].archiveSha256 = 'bad'; const report = verifyReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /candidate feed|generated manifest|npm provenance/); });
test('Svelte template receipt requires two identical journeys', () => { const value = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [receipt(), receipt()] }; assert.deepEqual(verifyRepeatedReceipt(value, authority), { ok: true, errors: [] }); value.journeys[1].phases[3].exitCode = 1; const report = verifyRepeatedReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join('\n'), /frontend-build|not deterministic/); });
