import assert from "node:assert/strict";
import test from "node:test";
import { NEGATIVE_GATE_EVIDENCE, NPM_CANDIDATES, NUGET_CANDIDATES, RECEIPT_SCHEMA, REPEAT_RECEIPT_SCHEMA, ROLLOUT, ROLLOUT_SHA256, verifyReceipt, verifyRepeatedReceipt } from "./verify.mjs";

const authority = { commit: "fixture", digest: "a".repeat(64), path: ".github/runic.release.json" };
const negativeGates = () => NEGATIVE_GATE_EVIDENCE.map((gate) => ({ ...structuredClone(gate), result: { status: "rejected", exitCode: 1, reasonCode: "command-exit-nonzero" } }));
const receipt = () => ({ schema: RECEIPT_SCHEMA, rollout: ROLLOUT, rolloutSha256: ROLLOUT_SHA256, releaseAuthority: authority, isolation: { nuget: ".nuget/packages", npm: ".npm-cache" }, nugetCandidates: NUGET_CANDIDATES.map((c) => ({ ...c, source: "w30-005-local-candidate-nuget-feed", contentHash: "sha512-fixture" })), npmCandidates: NPM_CANDIDATES.map((c) => ({ ...c, source: "w30-005-local-candidate-npm-feed", integrity: "sha512-fixture", archiveSha256: "b".repeat(64) })), negativeGates: negativeGates(), journey: ["baseline", "frontend-compatible", "asset-compatible", "locale-compatible", "baseline"], commands: [] });
test("rollout receipt binds the staged contract and authority", () => assert.deepEqual(verifyReceipt(receipt(), authority), { ok: true, errors: [] }));
test("rollout receipt rejects forged candidate, manifest, authority and contract evidence", () => { const value = receipt(); value.nugetCandidates[0].source = "public"; value.rollout = { ...ROLLOUT, contractFingerprint: "forged" }; value.releaseAuthority = { ...authority, digest: "f".repeat(64) }; const report = verifyReceipt(value, authority); assert.equal(report.ok, false); assert.match(report.errors.join("\n"), /rollout|authority|NuGet/); });
test("rollout receipt rejects missing, forged or softened negative-gate evidence", () => { const missing = receipt(); delete missing.negativeGates; assert.match(verifyReceipt(missing, authority).errors.join("\n"), /negative gate/); const forged = receipt(); forged.negativeGates[0].input.candidateVersion = "0.2.0-w30.4"; assert.match(verifyReceipt(forged, authority).errors.join("\n"), /negative gate/); const softened = receipt(); softened.negativeGates[1].result.status = "passed"; softened.negativeGates[1].result.exitCode = 0; assert.match(verifyReceipt(softened, authority).errors.join("\n"), /negative gate/); });
test("rollout receipt requires byte-identical double journeys", () => { const value = { schema: REPEAT_RECEIPT_SCHEMA, journeys: [receipt(), receipt()] }; assert.deepEqual(verifyRepeatedReceipt(value, authority), { ok: true, errors: [] }); value.journeys[1].journey[4] = "forged"; assert.match(verifyRepeatedReceipt(value, authority).errors.join("\n"), /not deterministic/); });
