// <auto-generated />
import { inject, type Provider } from "@angular/core";
import { AngularMvvmStore } from "@webuitoolkit/mvvm-angular";
import type { SimpleTodoContract, AdvancedTodoContract } from "../../shared/todo-contract.g.js";

export class SimpleTodoContractService {
  public readonly newTitle;
  public readonly newTitleErrors;
  public readonly items;
  public readonly add;
  public readonly toggle;
  public readonly remove;

  public constructor(
    public readonly store: AngularMvvmStore,
    public readonly contract: SimpleTodoContract,
  ) {
    this.newTitle = store.property(contract.newTitle);
    this.newTitleErrors = store.validation(contract.newTitle);
    this.items = store.collection(contract.items);
    this.add = store.commandFacade(contract.add);
    this.toggle = store.commandFacade(contract.toggle);
    this.remove = store.commandFacade(contract.remove);
  }
}

export function provideSimpleTodoContract(
  store: AngularMvvmStore,
  contract: SimpleTodoContract,
): readonly Provider[] {
  return [{ provide: SimpleTodoContractService, useFactory: () => new SimpleTodoContractService(store, contract) }];
}

export function injectSimpleTodoContract(): SimpleTodoContractService {
  return inject(SimpleTodoContractService);
}

export class AdvancedTodoContractService {
  public readonly newTitle;
  public readonly newTitleErrors;
  public readonly newNotes;
  public readonly newPriority;
  public readonly query;
  public readonly filter;
  public readonly items;
  public readonly diagnostics;
  public readonly state;
  public readonly add;
  public readonly applyFilter;
  public readonly toggle;
  public readonly delete;
  public readonly clearCompleted;
  public readonly import;
  public readonly cancelImport;
  public readonly wizardStart;
  public readonly wizardNext;
  public readonly wizardBack;
  public readonly wizardFinish;
  public readonly wizardCancel;

  public constructor(
    public readonly store: AngularMvvmStore,
    public readonly contract: AdvancedTodoContract,
  ) {
    this.newTitle = store.property(contract.newTitle);
    this.newTitleErrors = store.validation(contract.newTitle);
    this.newNotes = store.property(contract.newNotes);
    this.newPriority = store.property(contract.newPriority);
    this.query = store.property(contract.query);
    this.filter = store.property(contract.filter);
    this.items = store.collection(contract.items);
    this.diagnostics = store.collection(contract.diagnostics);
    this.state = store.property(contract.state);
    this.add = store.commandFacade(contract.add);
    this.applyFilter = store.commandFacade(contract.applyFilter);
    this.toggle = store.commandFacade(contract.toggle);
    this.delete = store.commandFacade(contract.delete);
    this.clearCompleted = store.commandFacade(contract.clearCompleted);
    this.import = store.commandFacade(contract.import);
    this.cancelImport = store.commandFacade(contract.cancelImport);
    this.wizardStart = store.commandFacade(contract.wizardStart);
    this.wizardNext = store.commandFacade(contract.wizardNext);
    this.wizardBack = store.commandFacade(contract.wizardBack);
    this.wizardFinish = store.commandFacade(contract.wizardFinish);
    this.wizardCancel = store.commandFacade(contract.wizardCancel);
  }
}

export function provideAdvancedTodoContract(
  store: AngularMvvmStore,
  contract: AdvancedTodoContract,
): readonly Provider[] {
  return [{ provide: AdvancedTodoContractService, useFactory: () => new AdvancedTodoContractService(store, contract) }];
}

export function injectAdvancedTodoContract(): AdvancedTodoContractService {
  return inject(AdvancedTodoContractService);
}
